const { LabyrinthTemplate } = require("../classes");
const { standardLabyrinthInfrastructure } = require("./shared");

const RARITIES = ["Cursed", "Common", "Rare"];

module.exports = new LabyrinthTemplate("Debug Dungeon",
	"Unaligned",
	"This labyrinth contains whatever the devs were testing most recently. Balance not guaranteed!",
	10,
	[10],
	Object.fromEntries(["Darkness", "Earth", "Fire", "Light", "Water", "Wind", "Unaligned"].map(essence => [essence, [
		"Creative Acorn",
		"Finesse Fiber",
	]])),
	{
		Darkness: Object.fromEntries(RARITIES.map(rarity => [rarity, [
			"Blood Aegis",
			"Toxic Blood Aegis",
			"Urgent Blood Aegis",
			"Fever Break",
			"Fatiguing Fever Break",
			"Unstoppable Fever Break",
			"Ring of Conquest",
			"Hearty Ring of Conquest",
			"Powerful Ring of Conquest",
			"Shadow of Confusion",
			"Incompatible Shadow of Confusion",
			"Shattering Shadow of Confusion",
			"Spiked Shield",
			"Furious Spiked Shield",
			"Reinforced Spiked Shield",
			"Vengeful Void",
			"Hexing Vengeful Void",
			"Numbing Vengeful Void",
			"War Cry",
			"Flanking War Cry",
			"Weakening War Cry",
			"Warhammer",
			"Fatiguing Warhammer",
			"Toxic Warhammer"
		]])),
		Earth: Object.fromEntries(RARITIES.map(rarity => [rarity, [
			"Bounty Fist",
			"Midas's Bounty Fist",
			"Thirsting Bounty Fist",
			"Carrot",
			"Balanced Carrot",
			"Guarding Carrot",
			"Flail",
			"Bouncing Flail",
			"Incompatible Flail",
			"Herb Basket",
			"Enticing Herb Basket",
			"Guarding Herb Basket",
			"Medicine",
			"Hastening Medicine",
			"Urgent Medicine",
			"Nature's Caprice",
			"Accurate Nature's Caprice",
			"Hearty Nature's Caprice",
			"Sandstorm Formation",
			"Balanced Sandstorm Formation",
			"Soothing Sandstorm Formation",
			"Smokescreen",
			"Chaining Smokescreen",
			"Double Smokescreen"
		]])),
		Fire: Object.fromEntries(RARITIES.map(rarity => [rarity, [
			"Bonfire Formation",
			"Charging Bonfire Formation",
			"Hastening Bonfire Formation",
			"Cloak",
			"Accurate Cloak",
			"Powerful Cloak",
			"Elemental Scroll",
			"Balanced Elemental Scroll",
			"Surpassing Elemental Scroll",
			"Flame Scythes",
			"Thief's Flame Scythes",
			"Toxic Flame Scythes",
			"Heat Weaken",
			"Numbing Heat Weaken",
			"Staggering Heat Weaken",
			"Longsword",
			"Double Longsword",
			"Lethal Longsword",
			"Musket",
			"Discounted Musket",
			"Hunter's Musket",
			"Overburn Explosion",
			"Accurate Overburn Explosion",
			"Unstoppable Overburn Explosion"
		]])),
		Light: Object.fromEntries(RARITIES.map(rarity => [rarity, [
			"Battle Standard",
			"Thief's Battle Standard",
			"Tormenting Battle Standard",
			"Encouragement",
			"Rallying Encouragement",
			"Vigorous Encouragement",
			"Forbidden Knowledge",
			"Enticing Forbidden Knowledge",
			"Soothing Forbidden Knowledge",
			"Illumination",
			"Balanced Illumination",
			"Inspiring Illumination",
			"Midas Staff",
			"Accelerating Midas Staff",
			"Discounted Midas Staff",
			"Parrying Dagger",
			"Devoted Parrying Dagger",
			"Hastening Parrying Dagger",
			"Reveal Flaw",
			"Distracting Reveal Flaw",
			"Numbing Reveal Flaw",
			"Ring of Knowledge",
			"Accurate Ring of Knowledge",
			"Swift Ring of Knowledge"
		]])),
		Water: Object.fromEntries(RARITIES.map(rarity => [rarity, [
			"Buckler",
			"Guarding Buckler",
			"Supportive Buckler",
			"Conjured Ice Pillar",
			"Devoted Conjured Ice Pillar",
			"Taunting Conjured Ice Pillar",
			"Medic's Kit",
			"Inspiring Medic's Kit",
			"Warning Medic's Kit",
			"Net Launcher",
			"Kinetic Net Launcher",
			"Staggering Net Launcher",
			"Universal Solution",
			"Steam Wall",
			"Supportive Steam Wall",
			"Vigilant Steam Wall",
			"Centering Universal Solution",
			"Tormenting Universal Solution",
			"Water's Stillness",
			"Accelerating Water's Stillness",
			"Cleansing Water's Stillness",
			"Wave Crash",
			"Disenchanting Wave Crash",
			"Fatiguing Wave Crash"
		]])),
		Wind: Object.fromEntries(RARITIES.map(rarity => [rarity, [
			"Arcane Sledge",
			"Fatiguing Arcane Sledge",
			"Kinetic Arcane Sledge",
			"Enchantment Siphon",
			"Flanking Enchantment Siphon",
			"Tormenting Enchantment Siphon",
			"Greatsword",
			"Chaining Greatsword",
			"Distracting Greatsword",
			"Lightning Staff",
			"Disenchanting Lightning Staff",
			"Hexing Lightning Staff",
			"Tempestuous Wrath",
			"Flanking Tempestuous Wrath",
			"Opportunist's Tempestuous Wrath",
			"Tornado Formation",
			"Charging Tornado Formation",
			"Supportive Tornado Formation",
			"Vacuum Implosion",
			"Shattering Vacuum Implosion",
			"Urgent Vacuum Implosion",
			"Wind Burst",
			"Inspiring Wind Burst",
			"Toxic Wind Burst"
		]])),
		Unaligned: Object.fromEntries(RARITIES.map(rarity => [rarity, [
			"Cursed Blade",
			"Cursed Shield",
			"Cursed Doll",
			"Cursed Bag",
			"Cursed Tome",
			"Cursed Grimore",
			"Cursed Scroll",
			"Boots of Comfort",
			"Mighty Gauntlet",
			"Scarf",
			"Wolf Ring",
			"Accurate Boots of Comfort",
			"Hearty Boots of Comfort",
			"Powerful Boots of Comfort",
			"Accurate Mighty Gauntlet",
			"Hearty Mighty Gauntlet",
			"Swift Mighty Gauntlet",
			"Hearty Scarf",
			"Powerful Scarf",
			"Swift Scarf",
			"Accurate Wolf Ring",
			"Powerful Wolf Ring",
			"Swift Wolf Ring"
		]]))
	},
	{
		// Rooms
		"Event": ["Apple Pie Wishing Well", "Door 1 or Door 2?", "Free Gold?", "Gear Collector", "Imp Contract Faire", "The Score Beggar", "Twin Pedestals", "Workshop", "Merchant", "Rest Site", "Library", "Treasure"],
		"Battle": ["Hawk Fight", "Frog Ranch", "Wild Fire-Arrow Frogs", "Mechabee Fight", "Slime Fight", "Tortoise Fight", "Meteor Knight Fight"],
		"Artifact Guardian": ["Brute Convention"],
		"Final Battle": ["Hall of Mirrors"],
		...standardLabyrinthInfrastructure
	}
);
